### PR TITLE
Create readme.txt (Bugreport)

### PR DESCRIPTION
**Pull request by ghost**
This file contains the error log to the installation. File cannot be found in Extensions store and is not able to install from the link linked on your github page.

### CODE REVIEW

**Comment by Youngermaster** [comment]
How did you install it? Because I didn't follow the link on the `README.md`, I mean, I went here:
image

Then I went here and I clicked at `DiscordRPforVS.vsix`:
image

After all that, I installed it:
image

**And *voilá* it worked:**
image

**Comment by Pythonic-Rainbow** [comment]
This is not how you use GitHub....

**Comment by ghost** [comment]
I do know that this is not really the best way to use github, I haven't been on my computer over the last days, please excuse the late reply.

On windows 10, I was having issues with the install, the latest version of msvs2022 doesn't support this extension as it is - according to the install errors - not compatible with that version of msvs.

**Comment by aliaksandrzianevich** [comment]
I use VS2022 (Current version: 17.0.1; Last update: 19.11.2021) and Windows 10 (Version 21H1; 19043.1348)
When installing, it gives an error: **"This extension cannot be installed for any of the installed products."**
Screenshot_1
### View Install Log
> 11/24/2021 12:29:51 PM - Microsoft VSIX Installer
11/24/2021 12:29:51 - ----------------------------------------- -
11/24/2021 12:29:51 PM - vsixinstaller.exe version:
11/24/2021 12:29:51 PM - 17.0.5226-preview5
11/24/2021 12:29:51 - ----------------------------------------- -
11/24/2021 12:29:51 PM - Command line parameters:
11/24/2021 12:29:51 PM - C: \ Program Files (x86) \ Microsoft Visual Studio \ Installer \ resources \ app \ ServiceHub \ Services \ Microsoft.VisualStudio.Setup.Service \ VSIXInstaller.exe, C: \ Users \ asp1r \ AppData \ Local \ Temp \ DiscordRPforVS-5.5.4-2.vsix
11/24/2021 12:29:51 - ----------------------------------------- -
11/24/2021 12:29:51 PM - Microsoft VSIX Installer
11/24/2021 12:29:51 - ----------------------------------------- -
11/24/2021 12:29:52 PM - Initializing Install ...
11/24/2021 12:29:52 PM - Extension details ...
11/24/2021 12:29:52 PM - Identifier: VisualDevelopment.drpcvs
11/24/2021 12:29:52 PM - Name: Discord Rich Presence
11/24/2021 12:29:52 PM - Author: 1TheNikita
11/24/2021 12:29:52 PM - Version: 5.5.4
11/24/2021 12:29:52 PM - Description: A Discord Rich Presence extension for Visual Studio 2017 and 2019.
11/24/2021 12:29:52 PM - Locale: en-US
11.24.2021 12:29:52 - MoreInfoURL: https://marketplace.visualstudio.com/items?itemName=1TheNikita.drpcvs2019
11/24/2021 12:29:52 PM - InstalledByMSI: False
11/24/2021 12:29:52 PM - SupportedFrameworkVersionRange: [4.5,)
11/24/2021 12:29:52 -
11/24/2021 12:29:52 PM - SignatureState: Unsigned
11/24/2021 12:29:52 PM - Supported Products:
11/24/2021 12:29:52 PM - Microsoft.VisualStudio.Community
11/24/2021 12:29:52 PM - Version: [15.0,)
11/24/2021 12:29:52 PM - ProductArchitecture: x86
11/24/2021 12:29:52 PM - Microsoft.VisualStudio.Enterprise
11/24/2021 12:29:52 PM - Version: [15.0,)
11/24/2021 12:29:52 PM - ProductArchitecture: x86
11/24/2021 12:29:52 PM - Microsoft.VisualStudio.Pro
11/24/2021 12:29:52 PM - Version: [15.0,)
11/24/2021 12:29:52 PM - ProductArchitecture: x86
11/24/2021 12:29:52 -
11/24/2021 12:29:52 PM - Links:
11/24/2021 12:29:52 PM - Prerequisites:
11/24/2021 12:29:52 - ----------------------------------------- --------------
11/24/2021 12:29:52 PM - Identifier: Microsoft.VisualStudio.Component.CoreEditor
11/24/2021 12:29:52 PM - Name: Visual Studio core editor
11/24/2021 12:29:52 PM - Version: [15.0,)
11/24/2021 12:29:52 -
11/24/2021 12:29:52 PM - Signature composition ...
11/24/2021 12:29:52 PM - Extension is not signed.
11/24/2021 12:29:52 -
11/24/2021 12:29:52 PM - Searching for applicable products ...
11/24/2021 12:29:52 PM - Installed Product Found - Global Location
11/24/2021 12:29:52 PM - Found Installed Product - Visual Studio Community 2022
11/24/2021 12:29:52 PM - VSIXInstaller.NoApplicableSKUsException: This extension could not be installed for any of the installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl (IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1 & skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData (String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1 & skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack (IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall (IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize (Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize ()
   at System.Threading.Tasks.Task`1.InnerInvoke ()
   at System.Threading.Tasks.Task.Execute ()
--- End of the stack trace from the previous location where the exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo (Exception exceptionObject)

**Pull request closed without merging**
